### ISSUE TITLE
ColorChooserButton....

### ISSUE THREAD

**Issue by PySimpleGUI** [yuuTilde/yuuLight#1]
Hi there...

I noticed you're importing tkinter and calling the color chooser dialog.

You can do the same operation without having to call tkinter yourself by using the PySimpleGUI `ColorChooserButton`. 

One trick for "chooser" buttons is to set the target to be a hidden `Input` element.  If you set that `Input` element to have events enabled, then you will get an event when the user chooses a color.

While I've got your attention..... adding a screenshot to your readme will definitely get people to stop in and take a look at what you've made.  Everyone loves a picture.

**Comment by yuuTilde** [comment]
thx <3

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/177328134-0fe06df1-c18f-4261-9eed-cdce02781e93.png)

Oh nice!  Thank you for adding the screenshot!  Awesome!
